"""
`View.export()` -- writing the standalone viewer.

The output is a directory of ordinary static files with no build step, no CDN and no
network access at runtime. Serve it from anywhere, or zip it and mail it. That
matters for the audience: a reconstruction that only exists while someone's laptop
is running a dev server is not a figure you can attach to a paper.

Size is not hidden. `export()` always reports what it wrote and names the dominant
term, because for a 1 Myr series over a billion years the boundary frames are ~77%
of the total and that is a trade worth seeing. It does not warn, refuse, or hold an
opinion -- the default stays 1 Myr because Boundary Frames are not interpolatable,
so coarsening produces a visible jump every step rather than a smooth approximation.
"""

import json
import os
import shutil

from .build import Builder
from . import script as view_script

HERE = os.path.dirname(os.path.abspath(__file__))
JS_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "js"))

INDEX_HTML = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="lib/explorer.css">
<style>html, body {{ margin: 0; height: 100%; overflow: hidden; }}</style>
</head>
<body>
<div id="app"></div>
<script type="module">
import {{ mountExplorer }} from './lib/explorer.js';

const app = document.getElementById('app');
try {{
  const recipe = await (await fetch('view.json')).json();
  await mountExplorer(recipe, app);
}} catch (err) {{
  console.error(err);
  app.textContent = 'Could not load: ' + err.message;
}}
</script>
</body>
</html>
'''

README = '''# {title}

A standalone reconstruction viewer, generated by `geode`. Everything it needs is in
this directory -- no build step, no network access at runtime.

    python3 -m http.server -d . 8000

then open http://localhost:8000. (A plain `file://` open will not work: the page
loads its data with `fetch`, which browsers block for local files.)

## What is here

    index.html    the page
    view.json     the recipe: every display decision, as data
    data/         the exported reconstruction
    lib/          petrify, vendored
    provenance/   the View Script, and whatever else was bundled

`view.json` is the interesting file. Change a colour in it and reload -- no
rebuild. Changing the reconstruction model or the time range is the one thing it
cannot do, because those are data, not display.

{caption}
'''


def _public(spec):
    """Strip the private keys a layer spec carries between Python and the exporter."""
    return {k: v for k, v in spec.items() if not k.startswith("_")}


def export(view, out_dir, quiet=False, cache=None, overwrite=True):
    out_dir = os.path.abspath(out_dir)
    builder = Builder(view, cache=cache, quiet=quiet)

    data_dir = os.path.join(out_dir, "data")
    lib_dir = os.path.join(out_dir, "lib")
    prov_dir = os.path.join(out_dir, "provenance")
    if overwrite:
        for sub in (data_dir, lib_dir, prov_dir):
            if os.path.exists(sub):
                shutil.rmtree(sub)
    for sub in (data_dir, lib_dir, prov_dir):
        os.makedirs(sub, exist_ok=True)

    if not quiet:
        print("building {}".format(out_dir))

    # -- data ---------------------------------------------------------------

    layers = []
    needs_series = any(lyr["kind"] in ("boundaries", "velocities")
                       for lyr in view._layers)
    series_dir = None
    if needs_series:
        b = next((l for l in view._layers if l["kind"] == "boundaries"), {})
        v = next((l for l in view._layers if l["kind"] == "velocities"), {})
        series_dir = builder.series(tessellate=b.get("tessellate", 0.5),
                                    healpix_n=v.get("healpixN", 8),
                                    delta_time=v.get("deltaTime", 1.0))

    for spec in view._layers:
        kind = spec["kind"]
        out = _public(spec)

        if kind == "ocean":
            layers.append(out)

        elif kind == "continents":
            src = builder.polygons(which=spec["which"], tolerance=spec["tolerance"])
            name = "{}.json".format(spec["which"])
            _copy(os.path.join(src, name), os.path.join(data_dir, name))
            out["url"] = "data/{}".format(name)
            layers.append(out)

        elif kind == "boundaries":
            _copy(os.path.join(series_dir, "boundaries.json"),
                  os.path.join(data_dir, "boundaries.json"))
            _copy(os.path.join(series_dir, "frames"),
                  os.path.join(data_dir, "frames"))
            out["url"] = "data/boundaries.json"
            layers.append(out)

        elif kind == "velocities":
            _copy(os.path.join(series_dir, "velocities.json"),
                  os.path.join(data_dir, "velocities.json"))
            out["url"] = "data/velocities.json"
            layers.append(out)

        elif kind == "points":
            src = builder.points(spec)
            name = "{}.json".format(spec["id"])
            _copy(os.path.join(src, "points.json"), os.path.join(data_dir, name))
            out["url"] = "data/{}".format(name)
            if "_style_js_path" in spec:
                _copy(spec["_style_js_path"],
                      os.path.join(data_dir, spec["styleJs"]))
                out["styleJs"] = "data/{}".format(spec["styleJs"])
            layers.append(out)

        else:
            raise ValueError("cannot export layer kind {!r}".format(kind))

    # -- charts --------------------------------------------------------------

    sources = []
    for i, chart in enumerate(view._charts):
        name = "chart{}.csv".format(i)
        path = os.path.join(data_dir, name)
        # isinstance BEFORE any ==: `frame == "boundary_length"` on a DataFrame is an
        # elementwise comparison, and `if` on the result raises rather than being
        # falsey. Ordering the branches the other way is a real bug that only bites
        # views with both a derived and a DataFrame chart.
        source = chart["data"]
        if not isinstance(source, str):
            _write_chart_csv(chart, path)
        elif source == "boundary_length":
            _copy(builder.boundary_length(), path)
        else:
            _copy(source, path)
        sources.append({"url": "data/{}".format(name), "series": chart["series"]})

    # -- recipe --------------------------------------------------------------

    recipe = {
        "explorer": 1,
        "title": view.title,
        "subtitle": view.subtitle,
        "projection": view.projection,
        "theme": view.theme_id,
        "camera": {"lon": view.centre[0], "lat": view.centre[1], "zoom": view.zoom},
        "time": {"start": view.start, "end": view.end, "step": view.step,
                 "initial": view.start_time, "playRate": view.default_play_rate()},
        "credit": {"model": view.reconstruction, "modelLabel": view.model_credit},
        "caption": view.caption_text,
        "layers": layers,
    }
    if sources:
        recipe["charts"] = {"mode": getattr(view, "chart_mode", "shade"),
                            "sources": sources}

    # -- provenance ----------------------------------------------------------

    # `role` lets the host (js/explorer.js) find these two specific files and give
    # each its own zero-context explanation, rather than matching on `title` text
    # (fragile) or treating every file identically (the View Script and the
    # notebook need to say very different things to a reader with no context).
    files = []
    script_text = view_script.render(view, out_dir=os.path.basename(out_dir))
    _write(os.path.join(prov_dir, "view_script.py"), script_text)
    files.append({"title": "View Script", "url": "provenance/view_script.py",
                  "role": "viewScript",
                  "note": "The exact code that produced this view, generated "
                          "automatically -- not written by hand, and not meant "
                          "to be run on its own."})

    if view._notebook and os.path.exists(view._notebook):
        name = os.path.basename(view._notebook)
        _copy(view._notebook, os.path.join(prov_dir, name))
        files.append({"title": "Author's notebook", "url": "provenance/{}".format(name),
                      "role": "notebook",
                      "note": "The full analysis, exactly as the author wrote it "
                              "-- the file to download and run to reproduce this "
                              "from scratch."})

    recipe["provenance"] = {"label": "View the code", "files": files,
                            "libraries": view._libraries}
    if view._notebook_steps:
        recipe["provenance"]["steps"] = view._notebook_steps
    if view._notebook_figures:
        figures = []
        for fig in view._notebook_figures:
            name = os.path.basename(fig["path"])
            _copy(fig["path"], os.path.join(prov_dir, name))
            figures.append({"url": "provenance/{}".format(name),
                            "caption": fig.get("caption")})
        recipe["provenance"]["figures"] = figures
    if view._notebook_requirements:
        recipe["provenance"]["requirements"] = view._notebook_requirements

    _write(os.path.join(out_dir, "view.json"),
           json.dumps(recipe, indent=2, default=str))

    # -- the page and the library --------------------------------------------

    _write(os.path.join(out_dir, "index.html"),
           INDEX_HTML.format(title=view.title))
    _write(os.path.join(out_dir, "README.md"),
           README.format(title=view.title, caption=view.caption_text or ""))

    for name in sorted(os.listdir(JS_DIR)):
        if name.endswith((".js", ".css")):
            _copy(os.path.join(JS_DIR, name), os.path.join(lib_dir, name))

    if not quiet:
        _report(out_dir)
    return out_dir


def _copy(src, dst):
    if os.path.isdir(src):
        shutil.copytree(src, dst, dirs_exist_ok=True)
    else:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)


def _write_chart_csv(chart, path):
    """A chart source from a DataFrame.

    `step=True` writes every row at BOTH ends of its interval. A plain line renderer
    then draws a proper stepped histogram -- a flat run across each bin's span and a
    near-vertical riser between neighbours -- without the chart library needing a bar
    mode for the sake of one page.
    """
    frame = chart["data"]
    time_col = chart["time"] or frame.columns[0]
    value_cols = list(chart["series"].keys())
    missing = [c for c in value_cols if c not in frame.columns]
    if missing:
        raise KeyError("timeseries frame has no column(s) {}".format(missing))

    rows = []
    times = list(frame[time_col])
    for i, t in enumerate(times):
        values = [frame[c].iloc[i] for c in value_cols]
        rows.append([t] + values)
        if chart["step"]:
            # The next bin's start, or one interval past the last.
            nxt = times[i + 1] if i + 1 < len(times) \
                else t + (t - times[i - 1] if i else 1)
            rows.append([nxt] + values)

    import csv
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["time_ma"] + value_cols)
        writer.writerows(rows)


def _report(out_dir):
    """What was written, and what dominates it."""
    sizes = {}
    total = 0
    for dirpath, _, names in os.walk(out_dir):
        for name in names:
            size = os.path.getsize(os.path.join(dirpath, name))
            total += size
            rel = os.path.relpath(dirpath, out_dir)
            bucket = "frames/" if rel.endswith("frames") else (
                os.path.join(rel, name) if rel != "." else name)
            sizes[bucket] = sizes.get(bucket, 0) + size

    print("\nwrote {} ({:.0f} MB)".format(out_dir, total / 1e6))
    for name, size in sorted(sizes.items(), key=lambda kv: -kv[1])[:6]:
        print("  {:<28s} {:6.1f} MB  {:3.0f}%".format(
            name, size / 1e6, 100 * size / max(total, 1)))
    print("\n  python3 -m http.server -d {} 8000".format(out_dir))
