"""
The View Script: the generated half of the provenance record.

The `View` logs every call, so this can emit a canonical, ordered, minimal script
that provably reproduces the view. That matters more than it sounds. A notebook is
not a reliable record of itself -- cells run out of order, get edited after running,
get deleted after the object they mutated is still live. This is generated from what
the object actually received, so it is faithful by construction and works
identically whether the calls came from a notebook, a script, or a chat session.

"Minimal" is doing real work here: setters called repeatedly while iterating
(`theme()` six times while choosing one) collapse to the one that won, so the script
reads as the decisions rather than the search.

What it is NOT is a transcript of the author's analysis. The data block that
produced the DataFrame lives in their notebook, which `View.notebook()` bundles
beside this; the libraries that did the science are named by `View.cites()`. A
script implying it contains all three would be worse than one that says which third
it is.
"""

import datetime

# Called for their effect on the recipe rather than to add a layer: only the last
# call to each can matter, so earlier ones are dropped.
IDEMPOTENT = {"theme", "caption", "playback"}

# Verbs whose first argument is positional in real use. Emitting `v.theme('ember')`
# as `v.theme(theme_id='ember')` would be valid Python and wrong as documentation --
# nobody writes it that way, and the script's whole job is to look like the code you
# would have written.
POSITIONAL = {
    "points": ["frame"],
    "background": ["image"],
    "theme": ["theme_id"],
    "caption": ["text"],
    "playback": ["myr_per_second"],
    "timeseries": ["data", "series"],
    "distance_heatmap": ["samples", "baseline"],
    "export": ["out_dir"],
}

# Positional arguments emitted as the caller's own variable name (bare, unquoted)
# rather than as a Python literal -- these are always DataFrames, never strings.
BARE_NAME = {"frame", "samples", "baseline"}

HEADER = '''"""
View Script -- generated by geode on {stamp}.

This is the exact sequence of calls that produced the viewer beside it, emitted
from the calls the View object actually received rather than transcribed from a
notebook. Re-running it against the same data reproduces the view.

What it does not contain: the analysis that produced `{frames}`. That lives in the
author's own notebook, and the packages it called are listed under "Analysis
libraries" in this drawer.
"""
import geode

'''


def render_value(value):
    """A Python literal for a logged argument."""
    if isinstance(value, Rule):
        return value.source
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, bool) or value is None:
        return repr(value)
    if isinstance(value, float):
        # 3.1 rather than 3.1000000000000001, and 300 rather than 300.0 -- a script
        # is read, and a float that came from arithmetic should not look like a
        # precision the caller asked for.
        value = round(value, 6)
        return repr(int(value) if value == int(value) else value)
    if isinstance(value, (int,)):
        return repr(value)
    if isinstance(value, tuple):
        return "({})".format(", ".join(render_value(v) for v in value))
    if isinstance(value, list):
        return "[{}]".format(", ".join(render_value(v) for v in value))
    if isinstance(value, dict):
        return "{{{}}}".format(", ".join(
            "{}: {}".format(render_value(k), render_value(v))
            for k, v in value.items()))
    return repr(value)


class Rule:
    """A Display Rule rendered as the call that builds it, not as its dict.

    `geode.age_window(5)` is the thing a reader can copy; `{'type': 'age_window',
    'window': 5.0, 'fade': 0.07}` is its serialisation, and putting the second in a
    script that teaches the API would teach the wrong half.
    """

    def __init__(self, source):
        self.source = source


def _as_rule(value):
    if not isinstance(value, dict) or "type" not in value:
        return value
    if value["type"] == "constant":
        return Rule("geode.constant()")
    if value["type"] == "age_window":
        args = [render_value(value["window"])]
        if abs(value.get("fade", 0.07) - 0.07) > 1e-9:
            args.append("fade={}".format(render_value(value["fade"])))
        return Rule("geode.age_window({})".format(", ".join(args)))
    return value


def _call(head, kwargs, verb=None):
    """`head(a, b=c)`, wrapped and aligned under the opening paren if it is long."""
    parts = []
    for name in POSITIONAL.get(verb, ()):
        if name not in kwargs:
            continue
        value = kwargs.pop(name)
        # A DataFrame cannot be a keyword literal, so it is logged as the name the
        # caller bound it to and emitted as that bare name.
        parts.append(str(value) if name in BARE_NAME
                     else render_value(_as_rule(value)))
    for name, value in kwargs.items():
        parts.append("{}={}".format(name, render_value(_as_rule(value))))

    one_line = "{}({})".format(head, ", ".join(parts))
    if len(one_line) <= 88:
        return one_line

    pad = " " * (len(head) + 1)
    return "{}({})".format(head, (",\n" + pad).join(parts))


def render(view, out_dir=None):
    """The whole script, as text."""
    log = list(view._log)

    # Keep only the last of each idempotent setter, in the position it last
    # appeared -- so a theme chosen after the layers reads after the layers.
    last = {}
    for i, entry in enumerate(log):
        if entry["verb"] in IDEMPOTENT:
            last[entry["verb"]] = i
    log = [e for i, e in enumerate(log)
           if e["verb"] not in IDEMPOTENT or last[e["verb"]] == i]

    frames = sorted({e["kwargs"].get("frame") for e in log
                     if e["verb"] == "points" and e["kwargs"].get("frame")})

    lines = [HEADER.format(
        stamp=datetime.date.today().isoformat(),
        frames=", ".join(frames) or "the input data")]

    for entry in log:
        kwargs = dict(entry["kwargs"])
        verb = entry["verb"]
        if verb == "globe":
            lines.append(_call("v = geode.globe", kwargs, verb))
        else:
            lines.append(_call("{}.{}".format(entry["receiver"] or "v", verb),
                               kwargs, verb))

    if out_dir:
        lines.append("")
        lines.append(_call("v.export", {"out_dir": out_dir}, "export"))

    return "\n".join(lines) + "\n"
